[package]
name = "piston_first"
version = "0.1.0"
authors = ["PiotrB <piotrb@gmail.com>"]

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
